--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/legolas20/Images/wallpapers/cherry_bloom.png"

-- Special
background="#242423"
foreground="#e2d2da"
cursor="#e2d2da"

-- Colors
color0="#242423"
color1="#92666F"
color2="#898A74"
color3="#AD768A"
color4="#AB999C"
color5="#CEA2B2"
color6="#BEC3B2"
color7="#e2d2da"
color8="#9e9398"
color9="#92666F"
color10="#898A74"
color11="#AD768A"
color12="#AB999C"
color13="#CEA2B2"
color14="#BEC3B2"
color15="#e2d2da"
