#!/bin/zsh

if [[ -z "$1" ]]; then
	echo "ERROR: No argument found"
	exit 1
else
	if [[ -e "$1" ]] && [[ -x "$1" ]]; then
		echo "for_window [instance=\"$1\"] floating enabled" >> ~/dotfiles/.config/i3/config
		$(i3-msg restart -q && ./"$1")
		sed -i "$ d" ~/dotfiles/.config/i3/config 
		$(i3-msg restart -q)
		exit 0
	else
		echo "ERROR: program does not exist/is not executable"
		exit 1
	fi
fi
