#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias -g lycee="/home/legolas20/Bureau/REMY/LYCEE/TS2"
alias -g cpge="/home/legolas20/Bureau/REMY/CPGE/SUP/"
alias -g yt="youtube-dl --add-metadata -i"
alias -g yta="yt -x -f bestaudio/best"
alias proj="cd /home/legolas20/code/scripts"
